name: Capstone ReactJS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 20

      # Thêm bước debug để kiểm tra phiên bản Node.js
      - name: Check Node.js Version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        run: |
          ssh user@your-server 'cd /path/to/deploy && git pull origin main'

      - name: Clean up
        run: npm prune